name: google_maps_markerwithlabel
description: MarkerWithLabel extends the Google Maps Marker class
version: 0.3.0
homepage: https://github.com/reyerstudio/google-maps-markerwithlabel
author: St√©phane Este-Gracias <sestegra@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  google_maps: ^3.3.1
  js_wrapping: ^0.5.0

dev_dependencies:
  build_runner: ^0.9.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.0
  html: ^0.13.3
  js_wrapping_generator: ^0.5.0
  test: ^1.3.0

#dependency_overrides:
#  js_wrapping:
#    path: ../dart-js-wrapping/js_wrapping
#  js_wrapping_generator:
#    path: ../dart-js-wrapping/js_wrapping_generator
